version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/dev/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - docker/dev/env/.dev.env
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql/
    env_file:
      - docker/dev/env/.db.env

volumes:
  mysql_data:
